//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CFXUnitTests.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.7.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CFX.Test.Listener")]
        public string ListenerHandle {
            get {
                return ((string)(this["ListenerHandle"]));
            }
            set {
                this["ListenerHandle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CFX.Test.Initiator")]
        public string ClientHandle {
            get {
                return ((string)(this["ClientHandle"]));
            }
            set {
                this["ClientHandle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("cfxtest")]
        public string DefaultUser {
            get {
                return ((string)(this["DefaultUser"]));
            }
            set {
                this["DefaultUser"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("cfxtestpassword")]
        public string DefaultPassword {
            get {
                return ((string)(this["DefaultPassword"]));
            }
            set {
                this["DefaultPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3faa6b00e8982499bafe87273d3e7647c388bad5")]
        public string CertificateThumbprint {
            get {
                return ((string)(this["CertificateThumbprint"]));
            }
            set {
                this["CertificateThumbprint"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CFXListener")]
        public string ListenerAddress {
            get {
                return ((string)(this["ListenerAddress"]));
            }
            set {
                this["ListenerAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5672")]
        public int CustomPort {
            get {
                return ((int)(this["CustomPort"]));
            }
            set {
                this["CustomPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("aishqcfx01v")]
        public string BrokerHostname {
            get {
                return ((string)(this["BrokerHostname"]));
            }
            set {
                this["BrokerHostname"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/exchange/CFXTestExchange")]
        public string BrokerExchange {
            get {
                return ((string)(this["BrokerExchange"]));
            }
            set {
                this["BrokerExchange"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/queue/CFXTestQueue")]
        public string BrokerQueue {
            get {
                return ((string)(this["BrokerQueue"]));
            }
            set {
                this["BrokerQueue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("cfxtest")]
        public string BrokerUsername {
            get {
                return ((string)(this["BrokerUsername"]));
            }
            set {
                this["BrokerUsername"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("cfxtest")]
        public string BrokerPassword {
            get {
                return ((string)(this["BrokerPassword"]));
            }
            set {
                this["BrokerPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("vhost:CFXTestHost")]
        public string BrokerVirtualHost {
            get {
                return ((string)(this["BrokerVirtualHost"]));
            }
            set {
                this["BrokerVirtualHost"] = value;
            }
        }
    }
}
